name: Test
on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.8
      uses: actions/setup-python@v4
      with:
        python-version: 3.8
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
    - name: metafx unique
      run: |
        export PATH=bin:$PATH
        chmod +x bin/metafx
        chmod +x bin/metafx-modules/*
        chmod +x bin/metafx-scripts/*
        metafx unique -t 2 -m 6G -k 31 -i test_data/sample_list.txt -w wd_unique
    - name: metafx metafast
      run: |
        export PATH=bin:$PATH
        chmod +x bin/metafx
        chmod +x bin/metafx-modules/*
        chmod +x bin/metafx-scripts/*
        metafx metafast -t 2 -m 6G -k 31 -i test_data/test/* test_data/3* test_data/4* -b1 200 -b2 5000 -l 50 -w wd_metafast
    - name: metafx colored
      run: |
        export PATH=bin:$PATH
        chmod +x bin/metafx
        chmod +x bin/metafx-modules/*
        chmod +x bin/metafx-scripts/*
        metafx colored -t 2 -m 6G -k 31 -i test_data/sample_list_3.txt --n-comps 100 --perc 0.7 -w wd_colored
    - name: metafx stats
      run: |
        export PATH=bin:$PATH
        chmod +x bin/metafx
        chmod +x bin/metafx-modules/*
        chmod +x bin/metafx-scripts/*
        metafx stats -t 2 -m 6G -k 31 -i test_data/sample_list.txt -w wd_stats
    - name: metafx metaspades
      run: |
        $CONDA/bin/conda env update --name base -c bioconda spades python=3.8
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
        export PATH=bin:$PATH
        chmod +x bin/metafx
        chmod +x bin/metafx-modules/*
        chmod +x bin/metafx-scripts/*
        metafx metaspades -t 2 -m 6G -k 31 -i test_data/33* -b1 100 -b2 1000 -l 50 -w wd_metaspades
